/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: F:\Boost\HIAB_UE53Chaos_Cust_Truck\Plugins\Lidar360GpuRayTracing\ThirdParty\ros2idl\generated/Header.h
  Source: F:\Boost\HIAB_UE53Chaos_Cust_Truck\Plugins\Lidar360GpuRayTracing\ThirdParty\ros2idl\idl\std_msgs/msg/Header.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_F__BOOST_HIAB_UE53CHAOS_CUST_TRUCK_PLUGINS_LIDAR360GPURAYTRACING_THIRDPARTY_ROS2IDL_GENERATED_HEADER_H_E78CD94F46896FD71328002D49CAFBAF
#define DDSC_F__BOOST_HIAB_UE53CHAOS_CUST_TRUCK_PLUGINS_LIDAR360GPURAYTRACING_THIRDPARTY_ROS2IDL_GENERATED_HEADER_H_E78CD94F46896FD71328002D49CAFBAF

#include "std_msgs/msg/Time.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct std_msgs_msg_Header
{
  struct std_msgs_msg_Time stamp;
  char * frame_id;
} std_msgs_msg_Header;

extern const dds_topic_descriptor_t std_msgs_msg_Header_desc;

#define std_msgs_msg_Header__alloc() \
((std_msgs_msg_Header*) dds_alloc (sizeof (std_msgs_msg_Header)));

#define std_msgs_msg_Header_free(d,o) \
dds_sample_free ((d), &std_msgs_msg_Header_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_F__BOOST_HIAB_UE53CHAOS_CUST_TRUCK_PLUGINS_LIDAR360GPURAYTRACING_THIRDPARTY_ROS2IDL_GENERATED_HEADER_H_E78CD94F46896FD71328002D49CAFBAF */
